--Checking if the connection & import were successful
SELECT *
FROM customers

-- Q1. What is the total revenue generated by Males vs Female customers?
SELECT gender, SUM(purchase_amount) as Total_Revenue
FROM customers
Group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'Yes'
AND purchase_amount > (select AVG(purchase_amount) from customers)

-- Q3. Top five products with the highest average review rating.
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating), 2) AS reviews
FROM customers
GROUP BY item_purchased
ORDER BY reviews DESC

-- Q4. Compare the average purchase amounts between standard and express shipping
-- Which shipping service produces substantial revenue?

SELECT shipping_type, AVG(purchase_amount)
FROM customers
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type

-- Q5. Do subscribed customers spend more? Compare average spending and total revenue between subscribers and non-subscribers.
SELECT subscription_status, count(customer_id) AS total_customers, 
	avg(purchase_amount) AS average_spend, sum(purchase_amount) AS total_revenue
FROM customers
GROUP BY subscription_status

-- Q6. Which products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE
	WHEN discount_applied = 'Yes' then 1
	else 0
END)/count(*),2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC

-- Q7. Where area generates the most revenue & how many purchases generated this revenue?
SELECT location, SUM(purchase_amount) AS total_area_revenue, SUM(previous_purchases) AS number_of_purchases
FROM customers
GROUP BY location
ORDER BY total_area_revenue DESC;

-- Q8. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and showing the count of each segment.
WITH customer_type AS(select customer_id, previous_purchases,
(CASE
	WHEN previous_purchases = 1 then 'New'
	WHEN previous_purchases between 2 AND 10 then 'Returning'
	else 'Loyal'
END) AS customer_segment
FROM customers)

SELECT customer_segment, count(customer_id) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q9. What are the top 3 most purchased products within each category?
WITH item_counts AS(SELECT category, item_purchased, 
	count(customer_id) AS total_orders, ROW_NUMBER() OVER (PARTITION BY category 
	ORDER BY count(customer_id) DESC) AS item_rank
FROM customers
GROUP BY category, item_purchased)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3

-- Q10. Are repeat buyers (more than 5 previous purchases) likely to subscribe?
SELECT Count(customer_id) AS repeat_buyers, subscription_status
FROM customers
WHERE subscription_status = 'Yes'
AND previous_purchases >= 5
GROUP BY subscription_status

-- Q11. What is the revenue contribution of each age group?
SELECT age_group, sum(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC


-- Creating column to add the segmentation data
ALTER TABLE customers
ADD customer_segment NVARCHAR(255);


UPDATE customers
SET customer_segment = CASE
	WHEN previous_purchases = 1 then 'New'
	WHEN previous_purchases between 2 AND 10 then 'Returning'
	else 'Loyal'
	END
